app:
  exchange-api:
    exchange-api-base-url: exchange-api-base-url
    cache-ttl: 60

  payment:
    linepay:
        base-url: https://sandbox-api-pay.line.me
        channel-id: channel-id
        channel-secret: channel-secret
    stripe:
      base-url: https://api.stripe.com
      secret-key: secret-key
      public-key: public-key
    jko:
      base-url: https://uat-onlinepay.jkopay.app
      merchant-id: merchant-id
      api-secret: api-secret
      api-key: api-key
spring:
  application:
    name: real-world-kt
  datasource:
    url: jdbc:postgresql://localhost:5431/real-world-kt
    username: postgres
    password: postgres

  jpa:
    hibernate:
#      need to change this
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6378
  cache:
    type: redis
